<?xml version="1.0"?>
<algebra>
    <brouwerianAlgebra>
        <algName>C3</algName>
        <desc>C3 as a Brouwerian algebra via poset</desc>
        <cardinality>3</cardinality>
        <labels>
            0,1,2
        </labels>
        <covArray>
            <cov c="[0]">1</cov>
            <cov c="[1]">2</cov>
            <cov c="[2]"></cov>
        </covArray>
    </brouwerianAlgebra>
</algebra>
