<?xml version="1.0"?>
<algebra>
    <pAlgebra>
        <algName>N5</algName>
        <desc>N5 as a p-algebra via poset</desc>
        <cardinality>5</cardinality>
        <labels>
            0,a,b,c,4
        </labels>
        <covArray>
            <cov c="[0]">a,c</cov>
            <cov c="[a]">b</cov>
            <cov c="[c]">4</cov>
            <cov c="[b]">4</cov>
            <cov c="[4]"></cov>
        </covArray>
    </pAlgebra>
</algebra>
