<?xml version="1.0"?>
<algebra>
    <basicLattice>
        <algName>M3</algName>
        <desc>M3 as a (basic) lattice</desc>
        <cardinality>5</cardinality>
        <labels>
            0,1,2,3,4
        </labels>
        <covArray>
            <cov c="[0]">1,2,3</cov>
            <cov c="[1]">4</cov>
            <cov c="[2]">4</cov>
            <cov c="[3]">4</cov>
            <cov c="[4]"></cov>
        </covArray>
    </basicLattice>
</algebra>