<?xml version="1.0"?>
<algebra>
    <brouwerianAlgebra>
        <algName>C5</algName>
        <desc>C5 as a Brouwerian algebra via poset</desc>
        <cardinality>5</cardinality>
        <labels>
            0,1,2,3,4
        </labels>
        <covArray>
            <cov c="[0]">1</cov>
            <cov c="[1]">2</cov>
            <cov c="[2]">3</cov>
            <cov c="[3]">4</cov>
            <cov c="[4]"></cov>
        </covArray>
    </brouwerianAlgebra>
</algebra>